// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcxVUk7MCbftEWE5RGIUfWV7vBdIosfw',
    appId: '1:862703291464:web:7528dda72393dd3a5a1c7d',
    messagingSenderId: '862703291464',
    projectId: 'agent-115a8',
    authDomain: 'agent-115a8.firebaseapp.com',
    storageBucket: 'agent-115a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChg43AW_S-mu185plYpuW3_MruRuOIPMs',
    appId: '1:862703291464:android:09e1fc88309b0fcc5a1c7d',
    messagingSenderId: '862703291464',
    projectId: 'agent-115a8',
    storageBucket: 'agent-115a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-rZE2dtP2dmWrCt59MxSU3kcPkrdzPIg',
    appId: '1:862703291464:ios:48a1c27edd5049355a1c7d',
    messagingSenderId: '862703291464',
    projectId: 'agent-115a8',
    storageBucket: 'agent-115a8.firebasestorage.app',
    iosBundleId: 'com.feelingpalette.feelingPalette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-rZE2dtP2dmWrCt59MxSU3kcPkrdzPIg',
    appId: '1:862703291464:ios:48a1c27edd5049355a1c7d',
    messagingSenderId: '862703291464',
    projectId: 'agent-115a8',
    storageBucket: 'agent-115a8.firebasestorage.app',
    iosBundleId: 'com.feelingpalette.feelingPalette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmcxVUk7MCbftEWE5RGIUfWV7vBdIosfw',
    appId: '1:862703291464:web:3179170fe346af0c5a1c7d',
    messagingSenderId: '862703291464',
    projectId: 'agent-115a8',
    authDomain: 'agent-115a8.firebaseapp.com',
    storageBucket: 'agent-115a8.firebasestorage.app',
  );

}